### ISSUE TITLE
No output when unable to book room 

### ISSUE THREAD

**Issue by vvattap** [cis3296s22/libraryroomscheduler#38]
I am using a Mac. The interface took me to the section to book the room but was unable to book a room as it was already full. I expected some output telling me that the room was already booked.

**Comment by bobby-palko** [comment]
Hey @vvattap. Our next release will delay the booking process, so it can grab times in the future immediately when Charles opens them up. You shouldn't have this issue after that release, and we're adding some additional error messages and logging to pinpoint any additional problems you may have. Let us know if you continue to have this issue after the next release is cut!
