### ISSUE TITLE
Couldn't get the cloned repo URL - program crashes

### ISSUE THREAD

**Issue by apsawicki** [cis3296s22/libraryroomscheduler#45]
stderr: 'fatal: unable to access 'https://github.com/cis3296s22/libraryroomscheduler.git/': The requested URL returned error: 403'

I think I got the right repo, i just clicked the green "code" button at the top right of the repo, then copy and pasted it into the section that told me to give it the link to the repo.

**Comment by apsawicki** [comment]
OS: windows 10
Python version: 3.10.4

**Comment by bobby-palko** [comment]
Hey @apsawicki! The URL you should be entering into the application is the URL of your private repo; this is where your booking data will be stored, and it's one of the prereqs on the README. I can see how this might be overlooked/confusing though, so I've introduced some feedback messages in the application that should help!
