### ISSUE TITLE
Does not run on Windows

### ISSUE THREAD

**Issue by SkylerShaw** [cis3296s22/libraryroomscheduler#8]
You claim that it runs on MacOS but I do not see a way to have it run on windows. Will there be windows functionality in the future?

**Comment by SkylerShaw** [comment]
This is on windows 10

**Comment by tuj79753** [comment]
It cannot run on my window either (Window 10).
How to run also only for MacOS, none for Windows.

**Comment by bobby-palko** [comment]
Run and build instructions have been added to the README.
